// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TYPE int32

const (
	TYPE_student TYPE = 0
	TYPE_teacher TYPE = 1
)

var TYPE_name = map[int32]string{
	0: "student",
	1: "teacher",
}
var TYPE_value = map[string]int32{
	"student": 0,
	"teacher": 1,
}

func (x TYPE) String() string {
	return proto.EnumName(TYPE_name, int32(x))
}
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_login_9be3b742067b8dc5, []int{0}
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Type                 TYPE     `protobuf:"varint,3,opt,name=type,proto3,enum=login.TYPE" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_9be3b742067b8dc5, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetType() TYPE {
	if m != nil {
		return m.Type
	}
	return TYPE_student
}

type LoginReply struct {
	Buffer               string   `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_9be3b742067b8dc5, []int{1}
}
func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (dst *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(dst, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetBuffer() string {
	if m != nil {
		return m.Buffer
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "login.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "login.LoginReply")
	proto.RegisterEnum("login.TYPE", TYPE_name, TYPE_value)
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_login_9be3b742067b8dc5) }

var fileDescriptor_login_9be3b742067b8dc5 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xd2, 0xb9, 0x78, 0x7c,
	0x40, 0x8c, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4,
	0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x1f, 0x24, 0x57,
	0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x5f, 0x94, 0x22, 0xc1, 0x04, 0x91, 0x83, 0xf1, 0x85, 0xe4, 0xb9,
	0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xb8, 0xf5, 0x20, 0x56,
	0x85, 0x44, 0x06, 0xb8, 0x06, 0x81, 0x25, 0x94, 0x54, 0xb8, 0xb8, 0xa0, 0x16, 0x15, 0xe4, 0x54,
	0x0a, 0x89, 0x71, 0xb1, 0x25, 0x95, 0xa6, 0xa5, 0xa5, 0x16, 0x41, 0x2d, 0x81, 0xf2, 0xb4, 0x14,
	0xb8, 0x58, 0x40, 0x7a, 0x84, 0xb8, 0xb9, 0xd8, 0x8b, 0x4b, 0x4a, 0x53, 0x52, 0xf3, 0x4a, 0x04,
	0x18, 0x40, 0x9c, 0x92, 0xd4, 0xc4, 0xe4, 0x8c, 0xd4, 0x22, 0x01, 0x46, 0x23, 0x1b, 0x2e, 0x56,
	0xb0, 0x39, 0x42, 0xc6, 0x5c, 0xec, 0x2e, 0xf9, 0x10, 0xa6, 0x30, 0xd4, 0x3a, 0x64, 0x9f, 0x48,
	0x09, 0xa2, 0x0a, 0x16, 0xe4, 0x54, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0x3d, 0x6f, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xd8, 0x71, 0x0b, 0xe6, 0x0b, 0x01, 0x00, 0x00,
}
