// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Arith.proto

//定义包名

package Arith

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArithRequest struct {
	A                    int32    `protobuf:"varint,1,opt,name=A,json=a,proto3" json:"A,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=B,json=b,proto3" json:"B,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArithRequest) Reset()         { *m = ArithRequest{} }
func (m *ArithRequest) String() string { return proto.CompactTextString(m) }
func (*ArithRequest) ProtoMessage()    {}
func (*ArithRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89835e6438b55cb, []int{0}
}

func (m *ArithRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArithRequest.Unmarshal(m, b)
}
func (m *ArithRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArithRequest.Marshal(b, m, deterministic)
}
func (m *ArithRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArithRequest.Merge(m, src)
}
func (m *ArithRequest) XXX_Size() int {
	return xxx_messageInfo_ArithRequest.Size(m)
}
func (m *ArithRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArithRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArithRequest proto.InternalMessageInfo

func (m *ArithRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *ArithRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type ArithReply struct {
	C                    int32    `protobuf:"varint,1,opt,name=C,json=c,proto3" json:"C,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArithReply) Reset()         { *m = ArithReply{} }
func (m *ArithReply) String() string { return proto.CompactTextString(m) }
func (*ArithReply) ProtoMessage()    {}
func (*ArithReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89835e6438b55cb, []int{1}
}

func (m *ArithReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArithReply.Unmarshal(m, b)
}
func (m *ArithReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArithReply.Marshal(b, m, deterministic)
}
func (m *ArithReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArithReply.Merge(m, src)
}
func (m *ArithReply) XXX_Size() int {
	return xxx_messageInfo_ArithReply.Size(m)
}
func (m *ArithReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ArithReply.DiscardUnknown(m)
}

var xxx_messageInfo_ArithReply proto.InternalMessageInfo

func (m *ArithReply) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

func init() {
	proto.RegisterType((*ArithRequest)(nil), "Arith.ArithRequest")
	proto.RegisterType((*ArithReply)(nil), "Arith.ArithReply")
}

func init() { proto.RegisterFile("Arith.proto", fileDescriptor_b89835e6438b55cb) }

var fileDescriptor_b89835e6438b55cb = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x76, 0x2c, 0xca, 0x2c,
	0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xb4, 0xb8, 0x78, 0xc0,
	0x8c, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x1e, 0x2e, 0x46, 0x47, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xd6, 0x20, 0xc6, 0x44, 0x10, 0xcf, 0x49, 0x82, 0x09, 0xc2, 0x4b, 0x52, 0x92, 0xe2,
	0xe2, 0x82, 0xaa, 0x2d, 0xc8, 0xa9, 0x04, 0xc9, 0x39, 0xc3, 0x54, 0x26, 0x27, 0xb1, 0x81, 0x4d,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xec, 0xf8, 0x5c, 0x64, 0x00, 0x00, 0x00,
}
