// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRole int32

const (
	UserRole_admin  UserRole = 0
	UserRole_normal UserRole = 1
)

var UserRole_name = map[int32]string{
	0: "admin",
	1: "normal",
}

var UserRole_value = map[string]int32{
	"admin":  0,
	"normal": 1,
}

func (x UserRole) String() string {
	return proto.EnumName(UserRole_name, int32(x))
}

func (UserRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role                 UserRole `protobuf:"varint,3,opt,name=role,proto3,enum=user.UserRole" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_admin
}

func init() {
	proto.RegisterEnum("user.UserRole", UserRole_name, UserRole_value)
	proto.RegisterType((*User)(nil), "user.user")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x92, 0xb8, 0xc0, 0xb4, 0x90,
	0x14, 0x17, 0x07, 0x88, 0xce, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82,
	0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x10, 0x39, 0x18,
	0x5f, 0x48, 0x89, 0x8b, 0xa5, 0x28, 0x3f, 0x27, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0xcf, 0x88,
	0x4f, 0x0f, 0x6c, 0x41, 0x68, 0x71, 0x6a, 0x51, 0x50, 0x7e, 0x4e, 0x6a, 0x10, 0x58, 0x4e, 0x4b,
	0x91, 0x8b, 0x03, 0x26, 0x22, 0xc4, 0xc9, 0xc5, 0x9a, 0x98, 0x92, 0x9b, 0x99, 0x27, 0xc0, 0x20,
	0xc4, 0xc5, 0xc5, 0x96, 0x97, 0x5f, 0x94, 0x9b, 0x98, 0x23, 0xc0, 0x98, 0xc4, 0x06, 0x76, 0x93,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x69, 0x4a, 0xa5, 0x2f, 0xa1, 0x00, 0x00, 0x00,
}
